### ISSUE TITLE
如何允许所有文件类型？

### ISSUE THREAD

**Issue by sunlewuyou** [jxnkwlp/SimpleStaticFileServer#1]
![image](https://user-images.githubusercontent.com/19728435/107154433-df354100-69ad-11eb-955e-0a9742695fd2.png)
有空的话还能改进一下吗？或者指点一下，谢谢！

**Comment by jxnkwlp** [comment]
可以的。 我有空修改下。

**Comment by jxnkwlp** [comment]
看了下代码，目前是可以添加配置类支持不同的文件类型的。
https://github.com/jxnkwlp/SimpleStaticFileServer/blob/f442b1ec04763fa399bfb2ce5c05f4d4205b9d0b/SimpleStaticFileServerForms/App.config#L6

按这里的配置，添加 exe 类型。
比如：
```
<add key="mime.exe" value="application/stream"/>
```

**Comment by sunlewuyou** [comment]
谢谢回复！新年快乐！

**Comment by jxnkwlp** [comment]
不客气

**Comment by sunlewuyou** [comment]
追问一下，请问如果要允许所有文件类型，有更简便的写法吗？

**Comment by jxnkwlp** [comment]
可以。需要修改代码。
参考 https://docs.microsoft.com/en-us/previous-versions/aspnet/dn782650(v=vs.113)#properties
设置 `ServeUnknownFileTypes` 和 `DefaultContentType` 。

**Comment by sunlewuyou** [comment]
再次感谢！！
